import "@/shared/styles/globals.css";

import { Inter } from "next/font/google";

import { NotificationSonner } from "@/features/notifications/ui/NotificationSonner";
import { GlobalProvider } from "@/features/ui/providers/GlobalProvider";
import { Header } from "@/features/ui/ui/header/Header";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

export default async function RootLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${inter.variable} antialiased`}
			suppressHydrationWarning
		>
			<body className="min-h-[144vh] flex flex-col">
				<GlobalProvider>
					<Header />
					<NotificationSonner />

					{children}
					{modal}
				</GlobalProvider>
			</body>
		</html>
	);
}
