import "@/shared/styles/globals.css";

import { Inter } from "next/font/google";

import { NotificationSonner } from "@/features/notifications/ui/NotificationSonner";
import { ThemesProvider } from "@/features/ui/providers/ThemesProvider";
import { Header } from "@/features/ui/ui/header/Header";
import { ReduxProvider } from "@/shared/model/ReduxProvider";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

export default async function RootLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${inter.variable} antialiased`}
			suppressHydrationWarning
		>
			<body className="min-h-[144vh] flex flex-col">
				<ReduxProvider>
					<ThemesProvider>
						<Header />
						<NotificationSonner />

						{children}
						{modal}
					</ThemesProvider>
				</ReduxProvider>
			</body>
		</html>
	);
}
